spring.application.name=NexusHr
server.port=${PORT:8080}

# data-base connectivity -
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
 
#hibernate configuration -
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
